apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-service
  namespace: debug
  labels:
    app: debug-service
spec:
  selector:
    matchLabels:
      name: debug-service
  template:
    metadata:
      labels:
        name: debug-service
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: debug-service
          image: nepooomuk/debug-service
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30